services:
  - type: web
    name: taxi-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /api/taxis
    envVars:
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: ALLOWED_ORIGINS
        value: "https://taxigo-app-nine.vercel.app" # Update this with your frontend URL after deployment

# databases:
#   - name: taxi-postgres
#     plan: free
#     databaseName: taxidb
#     user: taxi_user
