services:
  - type: web
    name: taxi-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /api/taxis
    envVars:
      - key: PORT
        value: 8085
      - key: SPRING_DATASOURCE_DRIVER
        value: org.postgresql.Driver
      - key: SPRING_JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: taxi-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: taxi-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: taxi-postgres
          property: password
      - key: ALLOWED_ORIGINS
        value: "*" # Update this with your frontend URL after deployment

databases:
  - name: taxi-postgres
    plan: free
    databaseName: taxidb
    user: taxi_user
